# Generated by Django 3.0.7 on 2020-06-22 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('lokasi', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=16)),
                ('ukuran', models.CharField(max_length=12)),
                ('expired', models.DateField()),
                ('tanggal_periksa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekanan', models.CharField(max_length=10)),
                ('tabung', models.CharField(max_length=2)),
                ('pin', models.CharField(max_length=2)),
                ('handle', models.CharField(max_length=2)),
                ('label', models.CharField(max_length=2)),
                ('selang', models.CharField(max_length=2)),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=300)),
                ('apar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparApp.Apar')),
            ],
        ),
    ]
