# Generated by Django 3.0.7 on 2020-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apar',
            name='expired',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='apar',
            name='tanggal_periksa',
            field=models.DateField(null=True),
        ),
    ]
