# Generated by Django 3.0.7 on 2020-06-22 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0004_auto_20200622_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='handle',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='label',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='pin',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='selang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tabung',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 22, 3, 1, 21, 862632, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tekanan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
