# Generated by Django 4.1.1 on 2022-09-20 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0007_alter_apar_ukuran_alter_pemeriksaan_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apar',
            name='ukuran',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 20, 6, 38, 54, 330513, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
