# Generated by Django 4.1.1 on 2022-09-21 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0008_alter_apar_ukuran_alter_pemeriksaan_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='apar',
            name='path_foto',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 21, 8, 51, 1, 586450, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
