# Generated by Django 4.2 on 2023-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0013_alter_pemeriksaan_handle_alter_pemeriksaan_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='handle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='label',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='selang',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tabung',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tekanan',
            field=models.BooleanField(default=False),
        ),
    ]
