# Generated by Django 4.2 on 2023-04-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0016_pemeriksaan_kartu_pemeriksaan_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaan',
            name='kartu',
        ),
    ]
