# Generated by Django 4.2 on 2023-04-14 07:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('aparApp', '0017_remove_pemeriksaan_kartu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apar',
            name='path_foto',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/202304/apar.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[280, 390], upload_to='images/%Y%m'),
        ),
    ]
