# Generated by Django 4.2 on 2023-05-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aparApp', '0019_pemeriksaan_path_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='pemeriksa',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
